FROM python:3.7-slim-buster
ENV FLASK_APP=tars
ENV FLASK_ENV=development

RUN pip install pip-tools && \
    mkdir /src

COPY ./ /src
WORKDIR /src

RUN pip install -e .

CMD ["flask", "run", "--host", "0.0.0.0"]
