FROM python:3.7-slim-buster
ENV FLASK_APP=tars
ENV FLASK_ENV=development

RUN pip install pip-tools && \
    mkdir /src

COPY ./ /src
WORKDIR /src

RUN pip install --require-hashes -r /src/requirements/requirements.txt

CMD ["flask", "run", "--host", "0.0.0.0"]
