version: "3"
services:
    tars:
        build:
            context: .
            dockerfile: ./Dockerfile.local
        command: 'flask run -h 0.0.0.0'
        image: tars 
        container_name: tars 
        ports: 
            - 5000:5000
        volumes:
            - ./:/src
        env_file: tars_env
